/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestOtpCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyOtpCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfileController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfileController_update"];
        trace?: never;
    };
    "/api/v1/dashboard-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardUserController_list"];
        put?: never;
        post: operations["DashboardUserController_provision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArticleController_list"];
        put?: never;
        post: operations["ArticleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArticleController_getBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ArticleController_get"];
        put?: never;
        post?: never;
        delete: operations["ArticleController_delete"];
        options?: never;
        head?: never;
        patch: operations["ArticleController_update"];
        trace?: never;
    };
    "/api/v1/articles/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ArticleController_updateStatus"];
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application and database health */
        get: operations["SystemController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverviewAnalyticsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_get"];
        put?: never;
        post?: never;
        delete: operations["AudienceController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_likes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_subscriptionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudienceController_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audience/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AudienceController_changeStatus"];
        trace?: never;
    };
    "/api/v1/audience/users/{id}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AudienceController_assignSubscription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscription-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubscriptionPlanController_list"];
        put?: never;
        post: operations["SubscriptionPlanController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscription-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["SubscriptionPlanController_update"];
        trace?: never;
    };
    "/api/v1/subscriptions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReaderSubscriptionController_getMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reader/articles/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReaderArticleController_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_list"];
        put?: never;
        post: operations["MediaController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media-assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MediaController_update"];
        trace?: never;
    };
    "/api/v1/notification-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationDraftController_list"];
        put?: never;
        post: operations["NotificationDraftController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notification-drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationDraftController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["NotificationDraftController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiMetaDto: {
            correlationId: string;
            /** Format: date-time */
            timestamp: string;
        };
        OtpChallengeResponseDto: {
            /** Format: uuid */
            challengeId: string;
            /** Format: date-time */
            expiresAt: string;
            /** @example 60 */
            resendAfterSeconds: number;
        };
        RequestOtpDto: {
            /**
             * @description Malawi phone number. National, country-code, and +265 inputs are accepted.
             * @example 265991234567
             */
            phoneNumber: string;
        };
        AdminAccessResponseDto: {
            /** @enum {string} */
            role: "admin" | "super_admin";
            /**
             * @example [
             *       "*"
             *     ]
             */
            permissions: string[];
        };
        ProfileResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example 265991234567 */
            phoneNumber: string;
            displayName: string | null;
            bio: string | null;
            avatarUrl: string | null;
            /** @example en */
            preferredLanguage: string;
            /** Format: date-time */
            phoneVerifiedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            adminAccess: components["schemas"]["AdminAccessResponseDto"] | null;
        };
        TokensResponseDto: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        VerifiedIdentityResponseDto: {
            profile: components["schemas"]["ProfileResponseDto"];
            tokens: components["schemas"]["TokensResponseDto"];
        };
        VerifyOtpCommandDto: {
            /** @example 123456 */
            code: string;
            /** Format: uuid */
            challengeId: string;
        };
        RefreshTokenDto: {
            refreshToken: string;
        };
        LogoutResponseDto: {
            /** @example true */
            loggedOut: boolean;
        };
        UpdateProfileDto: {
            displayName?: string | null;
            bio?: string | null;
            avatarUrl?: string | null;
            /** @enum {string} */
            preferredLanguage?: "en" | "ny";
        };
        DashboardUserResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            readerId: string;
            /** @example 265991234567 */
            phoneNumber: string;
            displayName: string | null;
            /** @enum {string} */
            role: "admin" | "super_admin";
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
        };
        DashboardUserCollectionResponseDto: {
            items: components["schemas"]["DashboardUserResponseDto"][];
            total: number;
        };
        ProvisionDashboardUserDto: {
            /** @example 0991234567 */
            phoneNumber: string;
            displayName?: string;
        };
        ArticleAuthorResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
        };
        ArticleSectionResponseDto: {
            /** Format: uuid */
            id: string;
            position: number;
            /** @enum {string} */
            type: "rich_text" | "image" | "youtube" | "advert";
            /**
             * @deprecated
             * @description Compatibility field for articles created by older authoring clients.
             */
            heading: string | null;
            body: string | null;
            mediaUrl: string | null;
            caption: string | null;
            altText: string | null;
            youtubeVideoId: string | null;
            advertPlacementCode: string | null;
        };
        ArticleResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example a-clear-specific-headline-9f5d4c3b */
            slug: string;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            availableTransitions: ("draft" | "published" | "archived")[];
            canDelete: boolean;
            version: number;
            title: string;
            summary: string;
            heroImageUrl: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            author: components["schemas"]["ArticleAuthorResponseDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sections: components["schemas"]["ArticleSectionResponseDto"][];
        };
        CreateArticleSectionDto: {
            /** @enum {string} */
            type: "rich_text" | "image" | "youtube" | "advert";
            /**
             * @deprecated
             * @description Compatibility field for older clients. New authoring surfaces omit section headings.
             */
            heading?: string;
            /** @description Markdown for rich-text sections. */
            body?: string;
            /** Format: uri */
            mediaUrl?: string;
            caption?: string;
            altText?: string;
            /** @example dQw4w9WgXcQ */
            youtubeVideoId?: string;
            /** @example article.inline.1 */
            advertPlacementCode?: string;
        };
        CreateArticleDto: {
            title: string;
            summary: string;
            /** Format: uri */
            heroImageUrl?: string;
            sections: components["schemas"]["CreateArticleSectionDto"][];
        };
        ArticleSummaryResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example a-clear-specific-headline-9f5d4c3b */
            slug: string;
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            availableTransitions: ("draft" | "published" | "archived")[];
            canDelete: boolean;
            version: number;
            title: string;
            summary: string;
            heroImageUrl: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            author: components["schemas"]["ArticleAuthorResponseDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sectionCount: number;
        };
        ArticleCollectionResponseDto: {
            items: components["schemas"]["ArticleSummaryResponseDto"][];
            total: number;
        };
        UpdateArticleDto: {
            title: string;
            summary: string;
            /** Format: uri */
            heroImageUrl?: string;
            sections: components["schemas"]["CreateArticleSectionDto"][];
            expectedVersion: number;
        };
        UpdateArticleStatusDto: {
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            expectedVersion: number;
        };
        AuditActorResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
            /** @example 265991234567 */
            phoneNumber: string;
        };
        AuditLogResponseDto: {
            /** Format: uuid */
            id: string;
            actor: components["schemas"]["AuditActorResponseDto"];
            action: string;
            resourceType: string;
            /** Format: uuid */
            resourceId: string;
            metadata: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogCollectionResponseDto: {
            items: components["schemas"]["AuditLogResponseDto"][];
            total: number;
        };
        ArticleAnalyticsDto: {
            total: number;
            draft: number;
            published: number;
            archived: number;
            createdLast7Days: number;
            publishedLast7Days: number;
        };
        IdentityAnalyticsDto: {
            totalReaders: number;
            readersJoinedLast7Days: number;
            activeDashboardUsers: number;
            activeSessions: number;
            disabledReaders: number;
        };
        SubscriptionAnalyticsDto: {
            activePlans: number;
            paidSubscribers: number;
            freeReaders: number;
            articleReadsToday: number;
            transactionsRecorded: number;
        };
        EngagementAnalyticsDto: {
            comments: number;
            likes: number;
        };
        ContentOperationsAnalyticsDto: {
            readyMediaAssets: number;
            archivedMediaAssets: number;
            notificationDrafts: number;
            cancelledNotificationDrafts: number;
        };
        OperationsAnalyticsDto: {
            totalArticleRevisions: number;
            activityLast24Hours: number;
        };
        OverviewAnalyticsResponseDto: {
            articles: components["schemas"]["ArticleAnalyticsDto"];
            identity: components["schemas"]["IdentityAnalyticsDto"];
            subscriptions: components["schemas"]["SubscriptionAnalyticsDto"];
            engagement: components["schemas"]["EngagementAnalyticsDto"];
            contentOperations: components["schemas"]["ContentOperationsAnalyticsDto"];
            operations: components["schemas"]["OperationsAnalyticsDto"];
        };
        EntitlementPlanResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            planType: "free" | "paid";
            /** @enum {string} */
            billingPeriod: "none" | "monthly" | "yearly";
            priceMinor: number;
            currency: string;
            dailyArticleLimit: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReaderEntitlementResponseDto: {
            plan: components["schemas"]["EntitlementPlanResponseDto"];
            /** @enum {string} */
            source: "free" | "assigned";
            /** Format: uuid */
            subscriptionId: string | null;
            /** Format: date-time */
            startsAt: string | null;
            /** Format: date-time */
            endsAt: string | null;
            articlesReadToday: number;
            articlesRemainingToday: number | null;
            administratorBypass: boolean;
            /** Format: date-time */
            resetsAt: string;
        };
        AudienceUserSummaryResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example 265991234567 */
            phoneNumber: string;
            displayName: string | null;
            avatarUrl: string | null;
            preferredLanguage: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
            /** @enum {string|null} */
            adminRole: "admin" | "super_admin" | null;
            activeSessions: number;
            /** Format: date-time */
            lastActiveAt: string | null;
            entitlement: components["schemas"]["ReaderEntitlementResponseDto"];
        };
        AudienceUserCollectionResponseDto: {
            items: components["schemas"]["AudienceUserSummaryResponseDto"][];
            total: number;
        };
        AudienceUserDetailResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example 265991234567 */
            phoneNumber: string;
            displayName: string | null;
            avatarUrl: string | null;
            preferredLanguage: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
            /** @enum {string|null} */
            adminRole: "admin" | "super_admin" | null;
            activeSessions: number;
            /** Format: date-time */
            lastActiveAt: string | null;
            entitlement: components["schemas"]["ReaderEntitlementResponseDto"];
            bio: string | null;
            /** Format: date-time */
            phoneVerifiedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ActivityArticleResponseDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
        };
        CommentActivityResponseDto: {
            /** Format: uuid */
            id: string;
            article: components["schemas"]["ActivityArticleResponseDto"];
            /** Format: date-time */
            createdAt: string;
            body: string;
            /** @enum {string} */
            status: "active" | "hidden" | "deleted";
            /** Format: date-time */
            updatedAt: string;
        };
        CommentActivityCollectionResponseDto: {
            items: components["schemas"]["CommentActivityResponseDto"][];
            total: number;
        };
        LikeActivityResponseDto: {
            /** Format: uuid */
            id: string;
            article: components["schemas"]["ActivityArticleResponseDto"];
            /** Format: date-time */
            createdAt: string;
        };
        LikeActivityCollectionResponseDto: {
            items: components["schemas"]["LikeActivityResponseDto"][];
            total: number;
        };
        ActivityPlanResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        ActivityActorResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
        };
        SubscriptionActivityResponseDto: {
            /** Format: uuid */
            id: string;
            plan: components["schemas"]["ActivityPlanResponseDto"];
            /** @enum {string} */
            status: "active" | "canceled" | "expired";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string | null;
            /** Format: date-time */
            assignedAt: string;
            assignedBy: components["schemas"]["ActivityActorResponseDto"];
        };
        SubscriptionActivityCollectionResponseDto: {
            items: components["schemas"]["SubscriptionActivityResponseDto"][];
            total: number;
        };
        TransactionActivityResponseDto: {
            /** Format: uuid */
            id: string;
            plan: components["schemas"]["ActivityPlanResponseDto"];
            /** Format: uuid */
            subscriptionId: string | null;
            /** @enum {string} */
            type: "charge" | "refund";
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded";
            amountMinor: number;
            currency: string;
            /** Format: date-time */
            occurredAt: string;
        };
        TransactionActivityCollectionResponseDto: {
            items: components["schemas"]["TransactionActivityResponseDto"][];
            total: number;
        };
        AudienceUserStatusResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            deletedAt: string | null;
        };
        UpdateAudienceUserStatusDto: {
            /** @enum {string} */
            status: "active" | "disabled";
        };
        AssignReaderSubscriptionDto: {
            /** Format: uuid */
            planId: string;
        };
        SubscriptionPlanResponseDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string | null;
            /** @enum {string} */
            planType: "free" | "paid";
            /** @enum {string} */
            billingPeriod: "none" | "monthly" | "yearly";
            priceMinor: number;
            currency: string;
            dailyArticleLimit: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
            subscriberCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SubscriptionPlanCollectionResponseDto: {
            items: components["schemas"]["SubscriptionPlanResponseDto"][];
        };
        CreateSubscriptionPlanDto: {
            /** @example mikozi-plus */
            code: string;
            /** @example Mikozi Plus */
            name: string;
            description?: string;
            /** @enum {string} */
            billingPeriod: "monthly" | "yearly";
            /** @description Price in integer minor units. */
            priceMinor: number;
            /** @example MWK */
            currency: string;
            /** @description Null means unlimited. */
            dailyArticleLimit?: number | null;
        };
        UpdateSubscriptionPlanDto: {
            name?: string;
            description?: string | null;
            /** @enum {string} */
            billingPeriod?: "none" | "monthly" | "yearly";
            priceMinor?: number;
            /** @example MWK */
            currency?: string;
            dailyArticleLimit?: number | null;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        MediaCreatorResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
        };
        MediaAssetResponseDto: {
            /** Format: uuid */
            id: string;
            title: string;
            altText: string;
            caption: string | null;
            /** Format: uri */
            sourceUrl: string;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
            fileName: string;
            sizeBytes: number | null;
            width: number | null;
            height: number | null;
            rightsHolder: string | null;
            /** Format: date-time */
            rightsExpiresAt: string | null;
            /** @enum {string} */
            status: "ready" | "archived";
            createdBy: components["schemas"]["MediaCreatorResponseDto"];
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MediaAssetCollectionResponseDto: {
            items: components["schemas"]["MediaAssetResponseDto"][];
            total: number;
        };
        CreateMediaAssetDto: {
            title: string;
            altText: string;
            caption?: string | null;
            /** Format: uri */
            sourceUrl: string;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
            fileName: string;
            sizeBytes?: number | null;
            width?: number | null;
            height?: number | null;
            rightsHolder?: string | null;
            /** Format: date-time */
            rightsExpiresAt?: string | null;
        };
        UpdateMediaAssetDto: {
            title?: string;
            altText?: string;
            caption?: string | null;
            /** Format: uri */
            sourceUrl?: string;
            /** @enum {string} */
            mimeType?: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
            fileName?: string;
            sizeBytes?: number | null;
            width?: number | null;
            height?: number | null;
            rightsHolder?: string | null;
            /** Format: date-time */
            rightsExpiresAt?: string | null;
            /** @enum {string} */
            status?: "ready" | "archived";
        };
        NotificationImageResponseDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uri */
            sourceUrl: string;
        };
        NotificationCreatorResponseDto: {
            /** Format: uuid */
            id: string;
            displayName: string | null;
        };
        NotificationDraftResponseDto: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            /** @enum {string} */
            priority: "low" | "normal" | "high" | "urgent";
            /** @enum {string} */
            targetType: "all_readers" | "dashboard_users" | "specific_readers";
            targetReaderIds: string[];
            /** @enum {string} */
            channel: "push";
            imageAsset: components["schemas"]["NotificationImageResponseDto"] | null;
            actionUrl: string | null;
            /** Format: date-time */
            scheduledAt: string | null;
            /** @enum {string} */
            status: "draft" | "cancelled";
            /** @enum {boolean} */
            deliveryConnected: false;
            createdBy: components["schemas"]["NotificationCreatorResponseDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NotificationDraftCollectionResponseDto: {
            items: components["schemas"]["NotificationDraftResponseDto"][];
            total: number;
        };
        CreateNotificationDraftDto: {
            title: string;
            body: string;
            /**
             * @default normal
             * @enum {string}
             */
            priority: "low" | "normal" | "high" | "urgent";
            /** @enum {string} */
            targetType: "all_readers" | "dashboard_users" | "specific_readers";
            targetReaderIds?: string[];
            /** Format: uuid */
            imageAssetId?: string | null;
            actionUrl?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
        };
        UpdateNotificationDraftDto: {
            title?: string;
            body?: string;
            /**
             * @default normal
             * @enum {string}
             */
            priority: "low" | "normal" | "high" | "urgent";
            /** @enum {string} */
            targetType?: "all_readers" | "dashboard_users" | "specific_readers";
            targetReaderIds?: string[];
            /** Format: uuid */
            imageAssetId?: string | null;
            actionUrl?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            /** @enum {string} */
            status?: "draft" | "cancelled";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_requestOtpCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOtpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OtpChallengeResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AuthController_verifyOtpCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpCommandDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["VerifiedIdentityResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokensResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LogoutResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LogoutResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ProfileController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProfileResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ProfileController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProfileResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    DashboardUserController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DashboardUserCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    DashboardUserController_provision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionDashboardUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DashboardUserResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                status?: "draft" | "published" | "archived";
                sortBy?: "title" | "status" | "createdAt" | "updatedAt";
                sortDirection?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_getBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_delete: {
        parameters: {
            query: {
                expectedVersion: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ArticleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ArticleController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AuditController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditLogCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    SystemController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverviewAnalyticsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OverviewAnalyticsResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                access?: "all" | "reader" | "admin";
                planId?: string;
                sortBy?: "displayName" | "createdAt" | "lastActiveAt";
                sortDirection?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AudienceUserCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AudienceUserDetailResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AudienceController_comments: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommentActivityCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_likes: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LikeActivityCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_subscriptionHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubscriptionActivityCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_transactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TransactionActivityCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAudienceUserStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AudienceUserStatusResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    AudienceController_assignSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignReaderSubscriptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReaderEntitlementResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    SubscriptionPlanController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubscriptionPlanCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    SubscriptionPlanController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionPlanDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubscriptionPlanResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    SubscriptionPlanController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionPlanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubscriptionPlanResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ReaderSubscriptionController_getMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReaderEntitlementResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    ReaderArticleController_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ArticleResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    MediaController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                status?: "ready" | "archived";
                mimeType?: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MediaAssetCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    MediaController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MediaAssetResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    MediaController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MediaAssetResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    MediaController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMediaAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MediaAssetResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    NotificationDraftController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
                status?: "draft" | "cancelled";
                priority?: "low" | "normal" | "high" | "urgent";
                targetType?: "all_readers" | "dashboard_users" | "specific_readers";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotificationDraftCollectionResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    NotificationDraftController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotificationDraftResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    NotificationDraftController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotificationDraftResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
    NotificationDraftController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotificationDraftResponseDto"];
                        meta: components["schemas"]["ApiMetaDto"];
                    };
                };
            };
        };
    };
}
